export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS  = 'LOGIN_SUCCESS';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CURRENT_USER = 'CURRENT_USER';

export const SHOW_ROOM = 'SHOW_ROOM';

export const FETCH_TICKERS = 'FETCH_TICKERS';
export const FETCH_TICKER = 'FETCH_TICKER';
export const UPDATE_TICKER = 'UPDATE_TICKER';
export const FETCH_GROUP = 'FETCH_GROUP';

export const FETCH_RESERVATIONS = 'FETCH_RESERVATIONS';
export const FETCH_RESERVATION = 'FETCH_RESERVATION';
export const UPDATE_RESERVATION = 'UPDATE_RESERVATION';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';
export const CREATE_RESERVATION = 'CREATE_RESERVSATION';
export const ACTIVE_RESERVATIONS = 'ACTIVE_RESERVATIONS';


export const FETCH_PORTFOLIOS = 'PORTFOLIOS_REQUEST';
export const FETCH_USER_PORTFOLIOS = 'USER_PORTFOLIOS';
export const FETCH_USER_SELECTED_PORTFOLIO = 'FETCH_USER_SELECTED_PORTFOLIO';
export const CLEAR_USER_SELECTED_PORTFOLIO = 'CLEAR_USER_SELECTED_PORTFOLIO';
export const FETCH_PORTFOLIO_SELECTED_ITEMS = 'FETCH_PORTFOLIO_SELECTED_ITEMS';

export const FETCH_TOTAL_USER_DATA = 'FETCH_TOTAL_USER_DATA';

export const FETCH_ROOMS = 'FETCH_ROOMS';
export const FETCH_ROOM = 'FETCH_ROOM'; 
export const REFRESH_ROOM = 'REFRESH_ROOM';
export const FETCH_ROOM_PRICES = 'FETCH_ROOM_PRICES';
export const CREATE_ROOM = 'CREATE_ROOM';
export const DELETE_ROOM = 'DELETE_ROOM';

export const FETCH_COSTUMERS = 'FETCH_COSTUMERS';
export const FETCH_COSTUMER = 'FETCH_COSTUMER';
export const UPDATE_COSTUMER = 'UPDATE_COSTUMER';
export const DELETE_COSTUMER = 'DELETE_COSTUMER';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';